# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "dmrdraft"
client_id = "f865159b391070ec0ad099bcbb561ac4"
application_url = "https://sold-secondary-geography-dm.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://sold-secondary-geography-dm.trycloudflare.com/auth/callback",
  "https://sold-secondary-geography-dm.trycloudflare.com/auth/shopify/callback",
  "https://sold-secondary-geography-dm.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rndmrishabh.myshopify.com"
